version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: restaurant-service-db
    environment:
      SA_PASSWORD: "Senh@001"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - restaurant-bridge

volumes:
  sqlserver_data:
    driver: local

networks:
  restaurant-bridge:
    external: true